version: "3.8"
services:
  db:
    image: "postgres:14.1-alpine"
    environment:
      - POSTGRES_DB=world_cup_2022
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    container_name: db
    hostname: db
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"

  django:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./server/main/.env
    command: ["/usr/src/app/entrypoint.sh"]
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    depends_on:
      - db

  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  postgres:
