# Generated by Django 4.1.3 on 2022-12-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=64)),
                ('lastName', models.CharField(max_length=64)),
                ('role', models.CharField(choices=[('1', 'Main Ref'), ('0', 'Line Ref')], max_length=64)),
            ],
            options={
                'db_table': 'referee',
            },
        ),
    ]
