version: "3"
services:
  db:
    image: "postgres:14.1-alpine"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    container_name: db
    hostname: db
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"

  django:
    build: .
    container_name: django
    ports:
      - "8000:8000"
    env_file:
      - ./main/.env
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    depends_on:
      - db

volumes:
  postgres:
