version: "3"
services:
  django:
    container_name: django
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  db:
    image: postgres
    restart: always
    depends_on:
      - django
    environment:
      POSTGRES_PASSWORD: example
