# Generated by Django 4.1.3 on 2022-12-03 12:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservationDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('seatId', models.IntegerField()),
                ('matchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'reservation',
                'unique_together': {('matchId', 'seatId')},
            },
        ),
    ]
