# Generated by Django 4.1.2 on 2022-12-03 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_reservationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 3, 13, 40, 52, 480350)),
        ),
    ]
