# Generated by Django 4.1.3 on 2022-12-03 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stadiums', '0001_initial'),
        ('referees', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startsAt', models.DateTimeField()),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadiums.stadium')),
            ],
            options={
                'db_table': 'match',
            },
        ),
        migrations.CreateModel(
            name='Match_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
                ('teamId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'db_table': 'match_team',
                'unique_together': {('matchId', 'teamId')},
            },
        ),
        migrations.CreateModel(
            name='Match_Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
                ('refereeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referees.referee')),
            ],
            options={
                'db_table': 'match_referee',
                'unique_together': {('matchId', 'refereeId')},
            },
        ),
    ]
