# Generated by Django 4.1.2 on 2022-12-03 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match_team',
            unique_together={('matchId', 'teamId')},
        ),
    ]
