# Generated by Django 4.1.3 on 2022-12-05 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_remove_match_startsat_match_matchdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='matchDate',
            new_name='match_date',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='matchTime',
            new_name='match_time',
        ),
    ]
