# Generated by Django 4.1.2 on 2022-12-03 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0001_initial'),
        ('matches', '0002_alter_match_team_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
                ('refereeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referees.referee')),
            ],
            options={
                'unique_together': {('matchId', 'refereeId')},
            },
        ),
    ]
