# Generated by Django 4.1.2 on 2022-12-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_rename_matchdate_match_match_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_time',
            field=models.TimeField(),
        ),
    ]
