# Generated by Django 4.1.3 on 2022-12-03 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('city', models.CharField(default='', max_length=32)),
                ('country', models.CharField(default='', max_length=32)),
                ('rows', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('seatsPerRow', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'stadium',
            },
        ),
    ]
