name: Deploy WorldCup Website

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build client docker image
        run: docker build ./client -t ahmedihab/worldcup-client:latest 
      - name: Build server docker image
        run: docker build ./server -t ahmedihab/worldcup-server:latest 
      - name: Push docker images
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ahmedihab/worldcup-client:latest
          docker push ahmedihab/worldcup-server:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH to Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd WorldCup2022_Reservation_Tickets
            git pull
            ./deploy/deploy.sh
